
import { Locale } from '@/lib/translations';
import '../globals.css';

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

interface LanguageLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}

export default async function LanguageLayout({
  children,
  params,
}: LanguageLayoutProps) {
  const { lang } = await params;
  return (
    <html lang={lang}>
      <body>
        {children}
      </body>
    </html>
  );
}